name: Single target CI Workflow

on:
  workflow_call:
    inputs:
      tagname:
        description: "Client tag name"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: get_json
        name: read JSON
        run: echo content=$(cat somemap.json) >> $GITHUB_OUTPUT

      - name: Configuration existence check
        uses: actions/github-script@v3
        if: ${{ !fromJson(steps.get_json.outputs.content)[inputs.tagname].var }}
        with:
          script: core.setFailed('Configuration not found')

      - name: read current property
        run: echo "${{fromJson(steps.get_json.outputs.content)[inputs.tagname].var}}"
