# This is a basic workflow to help you get started with Actions

name: Single target CI


on:
  [workflow_call, workflow_dispatch]
    inputs:
      tagName:
        description: 'Client tag name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: get_json
        name: read JSON
        run: echo content=$(cat somemap.json) >> $GITHUB_OUTPUT

      - name: read property
        run: echo "${{fromJson(steps.get_json.outputs.content).dev.var}}"
