name: manual CI

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Client tag name (for single target deployment)'
        default: ''
        required: false
        type: string

jobs:
  make-matrix-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Setting a matrix for single environment"
      if: ${{ github.event.inputs.tagName }}
      run: |
        echo "matrix={ \"include\": [ ${{ github.event.inputs.tagName }}" >> $GITHUB_OUTPUT

    - name: "Setting a matrix for all environments"
      if: ${{ !github.event.inputs.tagName }}
      run: |
        echo matrix=$(cat ./somelist.json) >> $GITHUB_OUTPUT

  show-the-matrix:
    runs-on: ubuntu-latest
    needs: make-matrix-list
    steps:
    - name: "show the output"
      run: |
        echo "${{ needs.make-matrix-list.outputs.matrix }}"
  # show-the-vars:
  #   runs-on: ubuntu-latest
  #   need: 
  #   - make-matrix-list
  #   - show-the-matrix
  #   strategy:
  #     matrix: ${{fromJson(needs.make-matrix-list.outputs.matrix)}}
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: "check the variable"
  #     - run: |
  #       echo "${{ fromJson(steps.set_var.outputs.packageJson).version }}"